default: &default
 adapter: postgresql
 encoding: unicode
 pool: 10
 username: postgres
 password: postgres
 host: localhost
 
development:
 <<: *default
 database: spree_ver_dev

test:
 <<: *default
 database: spree_ver_test
